services:
  windy-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elevator-simulation
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: python src/main.py